eureka.instance.hostname=localhost

#dont regist eureka's ip address
eureka.client.register-with-eureka=false
# no need to fetch the local copy of registry as it is the server itself, this will be true from client only
eureka.client.fetch-registry=false
server.port=8761